### ISSUE TITLE
Proposals for new fixes for 3.0

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#1063]
- [x] Correction in the design of Mu (outstroke has uneven angled endstroke in the different opszs)
related (https://github.com/googlefonts/googlesans-flex/issues/1049) 
- [x] Removal of inktraps in 6/9 in large opszs. related (https://github.com/googlefonts/googlesans-flex/issues/1052)
- [x] Slashlongcomb.case removed from workfile. It was originally created for the Oslash glyph but now, being decomposed is no longer in use
- [x] Design review of the rounding in certain glyphs in the 144-25-1-GD100 (CGJSƏ&§©€¢£Øẞȷ 5 /five.tf } /two.denominator /three.denominator /five.denominator /six.denominator /seven.denominator  / tildecomb.viet   /tildecomb.viet.case  /_registered-R /percentbar.tab  /percent.tf  /comp_eth /comp_eth_bar ð/  ordfemenine related (https://github.com/googlefonts/googlesans-flex/issues/1050)
- [x] open type issue with adotbelow related (https://github.com/googlefonts/googlesans-flex/issues/1061)
- [x] #1065
- [x] #1076
- [x] #1075

We should also discuss this:
https://github.com/googlefonts/googlesans-flex/issues/1071

Besides this, there are some proposals for spacing adjustments that will follow

**Comment by MariannaPaszkowska** [comment]
re: removing two useless anchors of n?
Are we sure they are useless? Which anchors are they?

**Comment by MariannaPaszkowska** [comment]
Re: as it is not used and not encoded it is desirable to remove Slashlongcomb.case , please proceed.

**Comment by MariannaPaszkowska** [comment]
IMO we should correct the consistency of the terminals across masters in the mi, and remove the ink traps in 144 as requested by the team. Is this a good time to introduce such changes @chrissimpkins ?

**Comment by chrissimpkins** [comment]
> correction interpolation diagonal Q

Do we have this documented in an issue on the tracker? What are we changing in the interpolation of the `Q`? Let's please open separate issues for each new change proposal across different glyph areas so that it is easier to track these changes going forward.  This will allow us to slot into different versioned release milestones more easily too. Ty!

**Comment by MariannaPaszkowska** [comment]
@chrissimpkins I requested visuals from @octaviopardo in this issue #1075

**Comment by MariannaPaszkowska** [comment]
Confirming that fixes are in.
Task nr 4.
![Image](https://github.com/user-attachments/assets/71084c77-69ce-4118-84f9-b53a632aea7f)
